### ISSUE TITLE
It doesn't work with iTunes, Netease Cloud Music and Tencent Music

### ISSUE THREAD

**Issue by cloudiful** [kitarolivier/KSoft.MediaInfo#1]
Hi, thank you for your amazing plugin, it works fantastic with Spotify and Microsoft Edge.
However, I found out that it doesn't work with iTunes, Netease Cloud Music and Tencent Music (mainstream music apps in China). "media_info_is_playing" was always "False" and the rest of variables are null no matter what I do. 
What can I do to solve this issue and what info can I provide to you?

System:
CPU: AMD Ryzen 5 3600
RAM: 2X16G 3200mhz

OS: Windows 11 Pro 21H2
Version: 22000.856 and 1000.22000.856.0 experience pack

Macro Deck:
Version: 2.12.0
Build: 221941808

iTunes:
Version: 12.12.4.1

Netease Cloud Music:
Version: 2.10.3 (Build:200198)

Looking forward to your reply!

**Comment by kitarolivier** [comment]
Hello,

Thank you for your message.

The program that plays music must be compliant with the  GlobalSystemMediaTransportControlsSession from windows, like spotify, most web browsers, vlc, media player, etc...

You can check if the programs you are using (iTunes, Netease Cloud Music and Tencent Music) are compatible with that API if the following works : using hardware keys on your keybard that works for volume control and stop/play/pause/next/prev should control the app, and the following popup should appear :
![image](https://user-images.githubusercontent.com/37141868/186089963-bf6bf17b-f2c0-4c14-ac35-ce9f307c7549.png)
If not, the program is not compliant and cannot be controlled or information cannot be retrieved with the api.

Regards,

Olivier.

**Comment by cloudiful** [comment]
I understand now, thank you so much for your reply!
